package com.wilson.nfc.mapper;

import com.wilson.nfc.model.Product;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Fri Jun 29 13:45:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Fri Jun 29 13:45:27 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Fri Jun 29 13:45:27 CST 2018
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Fri Jun 29 13:45:27 CST 2018
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Fri Jun 29 13:45:27 CST 2018
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Fri Jun 29 13:45:27 CST 2018
     */
    int updateByPrimaryKey(Product record);

    List<Product> selectByCategoryId(Integer categoryId);

    int selectProductByName(String name);

    int selectProductById(Integer id);

    Product selectProduct(Integer productId);
}