package com.wilson.nfc.mapper;

import com.wilson.nfc.model.Product;
import com.wilson.nfc.model.ProductWithBLOBs;
import com.wilson.nfc.model.Shipping;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int insert(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int insertSelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    ProductWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int updateByPrimaryKeySelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_product
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int updateByPrimaryKey(Product record);


    List<Product> selectByCategoryId(@Param("categoryId") Integer categoryId);
    //List<Shipping> selectByUserId(@Param("userId") Integer userId);

}