package com.wilson.nfc.mapper;

import com.wilson.nfc.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_user
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_user
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_user
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_user
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_user
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfc_user
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    int updateByPrimaryKey(User record);
}