package com.wilson.nfc.model;

import java.util.Date;

public class Cart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.product_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.quantity
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.checked
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_cart.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.id
     *
     * @return the value of nfc_cart.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.id
     *
     * @param id the value for nfc_cart.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.user_id
     *
     * @return the value of nfc_cart.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.user_id
     *
     * @param userId the value for nfc_cart.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.product_id
     *
     * @return the value of nfc_cart.product_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.product_id
     *
     * @param productId the value for nfc_cart.product_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.quantity
     *
     * @return the value of nfc_cart.quantity
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.quantity
     *
     * @param quantity the value for nfc_cart.quantity
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.checked
     *
     * @return the value of nfc_cart.checked
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.checked
     *
     * @param checked the value for nfc_cart.checked
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.extra1
     *
     * @return the value of nfc_cart.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.extra1
     *
     * @param extra1 the value for nfc_cart.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.extra2
     *
     * @return the value of nfc_cart.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.extra2
     *
     * @param extra2 the value for nfc_cart.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.extra3
     *
     * @return the value of nfc_cart.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra3() {
        return extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.extra3
     *
     * @param extra3 the value for nfc_cart.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra3(String extra3) {
        this.extra3 = extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.create_time
     *
     * @return the value of nfc_cart.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.create_time
     *
     * @param createTime the value for nfc_cart.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_cart.update_time
     *
     * @return the value of nfc_cart.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_cart.update_time
     *
     * @param updateTime the value for nfc_cart.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}