package com.wilson.nfc.model;

import java.util.Date;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.sort_order
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_category.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.id
     *
     * @return the value of nfc_category.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.id
     *
     * @param id the value for nfc_category.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.name
     *
     * @return the value of nfc_category.name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.name
     *
     * @param name the value for nfc_category.name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.status
     *
     * @return the value of nfc_category.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.status
     *
     * @param status the value for nfc_category.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.extra1
     *
     * @return the value of nfc_category.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.extra1
     *
     * @param extra1 the value for nfc_category.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.extra2
     *
     * @return the value of nfc_category.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.extra2
     *
     * @param extra2 the value for nfc_category.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.extra3
     *
     * @return the value of nfc_category.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra3() {
        return extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.extra3
     *
     * @param extra3 the value for nfc_category.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra3(String extra3) {
        this.extra3 = extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.sort_order
     *
     * @return the value of nfc_category.sort_order
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.sort_order
     *
     * @param sortOrder the value for nfc_category.sort_order
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.create_time
     *
     * @return the value of nfc_category.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.create_time
     *
     * @param createTime the value for nfc_category.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_category.update_time
     *
     * @return the value of nfc_category.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_category.update_time
     *
     * @param updateTime the value for nfc_category.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}