package com.wilson.nfc.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.product_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.product_name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.product_image
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String productImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.current_unit_price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private BigDecimal currentUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.discount
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.mantissa
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private BigDecimal mantissa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.quantity
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.total_price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order_item.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.id
     *
     * @return the value of nfc_order_item.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.id
     *
     * @param id the value for nfc_order_item.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.user_id
     *
     * @return the value of nfc_order_item.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.user_id
     *
     * @param userId the value for nfc_order_item.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.order_no
     *
     * @return the value of nfc_order_item.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.order_no
     *
     * @param orderNo the value for nfc_order_item.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.product_id
     *
     * @return the value of nfc_order_item.product_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.product_id
     *
     * @param productId the value for nfc_order_item.product_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.product_name
     *
     * @return the value of nfc_order_item.product_name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.product_name
     *
     * @param productName the value for nfc_order_item.product_name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.product_image
     *
     * @return the value of nfc_order_item.product_image
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.product_image
     *
     * @param productImage the value for nfc_order_item.product_image
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.current_unit_price
     *
     * @return the value of nfc_order_item.current_unit_price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public BigDecimal getCurrentUnitPrice() {
        return currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.current_unit_price
     *
     * @param currentUnitPrice the value for nfc_order_item.current_unit_price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCurrentUnitPrice(BigDecimal currentUnitPrice) {
        this.currentUnitPrice = currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.discount
     *
     * @return the value of nfc_order_item.discount
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.discount
     *
     * @param discount the value for nfc_order_item.discount
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.mantissa
     *
     * @return the value of nfc_order_item.mantissa
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public BigDecimal getMantissa() {
        return mantissa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.mantissa
     *
     * @param mantissa the value for nfc_order_item.mantissa
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setMantissa(BigDecimal mantissa) {
        this.mantissa = mantissa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.quantity
     *
     * @return the value of nfc_order_item.quantity
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.quantity
     *
     * @param quantity the value for nfc_order_item.quantity
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.total_price
     *
     * @return the value of nfc_order_item.total_price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.total_price
     *
     * @param totalPrice the value for nfc_order_item.total_price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.extra1
     *
     * @return the value of nfc_order_item.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.extra1
     *
     * @param extra1 the value for nfc_order_item.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.extra2
     *
     * @return the value of nfc_order_item.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.extra2
     *
     * @param extra2 the value for nfc_order_item.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.extra3
     *
     * @return the value of nfc_order_item.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra3() {
        return extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.extra3
     *
     * @param extra3 the value for nfc_order_item.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra3(String extra3) {
        this.extra3 = extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.create_time
     *
     * @return the value of nfc_order_item.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.create_time
     *
     * @param createTime the value for nfc_order_item.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order_item.update_time
     *
     * @return the value of nfc_order_item.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order_item.update_time
     *
     * @param updateTime the value for nfc_order_item.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}