package com.wilson.nfc.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.shipping_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer shippingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.payment
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.discount
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.mantissa
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private BigDecimal mantissa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.payment_type
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.postage
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer postage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.payment_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.send_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.end_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.close_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_order.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.id
     *
     * @return the value of nfc_order.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.id
     *
     * @param id the value for nfc_order.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.order_no
     *
     * @return the value of nfc_order.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.order_no
     *
     * @param orderNo the value for nfc_order.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.user_id
     *
     * @return the value of nfc_order.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.user_id
     *
     * @param userId the value for nfc_order.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.shipping_id
     *
     * @return the value of nfc_order.shipping_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.shipping_id
     *
     * @param shippingId the value for nfc_order.shipping_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setShippingId(Integer shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.payment
     *
     * @return the value of nfc_order.payment
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.payment
     *
     * @param payment the value for nfc_order.payment
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.discount
     *
     * @return the value of nfc_order.discount
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.discount
     *
     * @param discount the value for nfc_order.discount
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.mantissa
     *
     * @return the value of nfc_order.mantissa
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public BigDecimal getMantissa() {
        return mantissa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.mantissa
     *
     * @param mantissa the value for nfc_order.mantissa
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setMantissa(BigDecimal mantissa) {
        this.mantissa = mantissa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.payment_type
     *
     * @return the value of nfc_order.payment_type
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.payment_type
     *
     * @param paymentType the value for nfc_order.payment_type
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.postage
     *
     * @return the value of nfc_order.postage
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.postage
     *
     * @param postage the value for nfc_order.postage
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.status
     *
     * @return the value of nfc_order.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.status
     *
     * @param status the value for nfc_order.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.payment_time
     *
     * @return the value of nfc_order.payment_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.payment_time
     *
     * @param paymentTime the value for nfc_order.payment_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.send_time
     *
     * @return the value of nfc_order.send_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.send_time
     *
     * @param sendTime the value for nfc_order.send_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.end_time
     *
     * @return the value of nfc_order.end_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.end_time
     *
     * @param endTime the value for nfc_order.end_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.close_time
     *
     * @return the value of nfc_order.close_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.close_time
     *
     * @param closeTime the value for nfc_order.close_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.extra1
     *
     * @return the value of nfc_order.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.extra1
     *
     * @param extra1 the value for nfc_order.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.extra2
     *
     * @return the value of nfc_order.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.extra2
     *
     * @param extra2 the value for nfc_order.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.extra3
     *
     * @return the value of nfc_order.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra3() {
        return extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.extra3
     *
     * @param extra3 the value for nfc_order.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra3(String extra3) {
        this.extra3 = extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.create_time
     *
     * @return the value of nfc_order.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.create_time
     *
     * @param createTime the value for nfc_order.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_order.update_time
     *
     * @return the value of nfc_order.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_order.update_time
     *
     * @param updateTime the value for nfc_order.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}