package com.wilson.nfc.model;

import java.util.Date;

public class PayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.pay_platform
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer payPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.platform_number
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String platformNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.platform_status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String platformStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_pay_info.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.id
     *
     * @return the value of nfc_pay_info.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.id
     *
     * @param id the value for nfc_pay_info.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.user_id
     *
     * @return the value of nfc_pay_info.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.user_id
     *
     * @param userId the value for nfc_pay_info.user_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.order_no
     *
     * @return the value of nfc_pay_info.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.order_no
     *
     * @param orderNo the value for nfc_pay_info.order_no
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.pay_platform
     *
     * @return the value of nfc_pay_info.pay_platform
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.pay_platform
     *
     * @param payPlatform the value for nfc_pay_info.pay_platform
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setPayPlatform(Integer payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.platform_number
     *
     * @return the value of nfc_pay_info.platform_number
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getPlatformNumber() {
        return platformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.platform_number
     *
     * @param platformNumber the value for nfc_pay_info.platform_number
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setPlatformNumber(String platformNumber) {
        this.platformNumber = platformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.platform_status
     *
     * @return the value of nfc_pay_info.platform_status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getPlatformStatus() {
        return platformStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.platform_status
     *
     * @param platformStatus the value for nfc_pay_info.platform_status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setPlatformStatus(String platformStatus) {
        this.platformStatus = platformStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.extra1
     *
     * @return the value of nfc_pay_info.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.extra1
     *
     * @param extra1 the value for nfc_pay_info.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.extra2
     *
     * @return the value of nfc_pay_info.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.extra2
     *
     * @param extra2 the value for nfc_pay_info.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.extra3
     *
     * @return the value of nfc_pay_info.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra3() {
        return extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.extra3
     *
     * @param extra3 the value for nfc_pay_info.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra3(String extra3) {
        this.extra3 = extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.create_time
     *
     * @return the value of nfc_pay_info.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.create_time
     *
     * @param createTime the value for nfc_pay_info.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_pay_info.update_time
     *
     * @return the value of nfc_pay_info.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_pay_info.update_time
     *
     * @param updateTime the value for nfc_pay_info.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}