package com.wilson.nfc.model;

public class ProductWithBLOBs extends Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.sub_images
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String subImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.detail
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.sub_images
     *
     * @return the value of nfc_product.sub_images
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getSubImages() {
        return subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.sub_images
     *
     * @param subImages the value for nfc_product.sub_images
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setSubImages(String subImages) {
        this.subImages = subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.detail
     *
     * @return the value of nfc_product.detail
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.detail
     *
     * @param detail the value for nfc_product.detail
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }
}