package com.wilson.nfc.model;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.category_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.subtitle
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.main_image
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String mainImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.stock
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String extra3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.type
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.uuid
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_product.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.id
     *
     * @return the value of nfc_product.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.id
     *
     * @param id the value for nfc_product.id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.category_id
     *
     * @return the value of nfc_product.category_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.category_id
     *
     * @param categoryId the value for nfc_product.category_id
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.name
     *
     * @return the value of nfc_product.name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.name
     *
     * @param name the value for nfc_product.name
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.subtitle
     *
     * @return the value of nfc_product.subtitle
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.subtitle
     *
     * @param subtitle the value for nfc_product.subtitle
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.main_image
     *
     * @return the value of nfc_product.main_image
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.main_image
     *
     * @param mainImage the value for nfc_product.main_image
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.price
     *
     * @return the value of nfc_product.price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.price
     *
     * @param price the value for nfc_product.price
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.stock
     *
     * @return the value of nfc_product.stock
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.stock
     *
     * @param stock the value for nfc_product.stock
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.extra1
     *
     * @return the value of nfc_product.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.extra1
     *
     * @param extra1 the value for nfc_product.extra1
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.extra2
     *
     * @return the value of nfc_product.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.extra2
     *
     * @param extra2 the value for nfc_product.extra2
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.extra3
     *
     * @return the value of nfc_product.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getExtra3() {
        return extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.extra3
     *
     * @param extra3 the value for nfc_product.extra3
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setExtra3(String extra3) {
        this.extra3 = extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.type
     *
     * @return the value of nfc_product.type
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.type
     *
     * @param type the value for nfc_product.type
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.uuid
     *
     * @return the value of nfc_product.uuid
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.uuid
     *
     * @param uuid the value for nfc_product.uuid
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.status
     *
     * @return the value of nfc_product.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.status
     *
     * @param status the value for nfc_product.status
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.create_time
     *
     * @return the value of nfc_product.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.create_time
     *
     * @param createTime the value for nfc_product.create_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_product.update_time
     *
     * @return the value of nfc_product.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_product.update_time
     *
     * @param updateTime the value for nfc_product.update_time
     *
     * @mbggenerated Thu Jun 21 21:30:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}