package com.wilson.nfc.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.id
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.username
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.password
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.email
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.phone
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.question
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.answer
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.role
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.nickname
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.uuid
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.extra1
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String extra1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.extra2
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String extra2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.extra3
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String extra3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.headimg
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private String headimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.create_time
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfc_user.update_time
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.id
     *
     * @return the value of nfc_user.id
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.id
     *
     * @param id the value for nfc_user.id
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.username
     *
     * @return the value of nfc_user.username
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.username
     *
     * @param username the value for nfc_user.username
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.password
     *
     * @return the value of nfc_user.password
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.password
     *
     * @param password the value for nfc_user.password
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.email
     *
     * @return the value of nfc_user.email
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.email
     *
     * @param email the value for nfc_user.email
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.phone
     *
     * @return the value of nfc_user.phone
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.phone
     *
     * @param phone the value for nfc_user.phone
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.question
     *
     * @return the value of nfc_user.question
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.question
     *
     * @param question the value for nfc_user.question
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.answer
     *
     * @return the value of nfc_user.answer
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.answer
     *
     * @param answer the value for nfc_user.answer
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.role
     *
     * @return the value of nfc_user.role
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.role
     *
     * @param role the value for nfc_user.role
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.nickname
     *
     * @return the value of nfc_user.nickname
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.nickname
     *
     * @param nickname the value for nfc_user.nickname
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.uuid
     *
     * @return the value of nfc_user.uuid
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.uuid
     *
     * @param uuid the value for nfc_user.uuid
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.extra1
     *
     * @return the value of nfc_user.extra1
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.extra1
     *
     * @param extra1 the value for nfc_user.extra1
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.extra2
     *
     * @return the value of nfc_user.extra2
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.extra2
     *
     * @param extra2 the value for nfc_user.extra2
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.extra3
     *
     * @return the value of nfc_user.extra3
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getExtra3() {
        return extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.extra3
     *
     * @param extra3 the value for nfc_user.extra3
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setExtra3(String extra3) {
        this.extra3 = extra3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.headimg
     *
     * @return the value of nfc_user.headimg
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.headimg
     *
     * @param headimg the value for nfc_user.headimg
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.create_time
     *
     * @return the value of nfc_user.create_time
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.create_time
     *
     * @param createTime the value for nfc_user.create_time
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfc_user.update_time
     *
     * @return the value of nfc_user.update_time
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfc_user.update_time
     *
     * @param updateTime the value for nfc_user.update_time
     *
     * @mbggenerated Thu Jun 21 10:45:17 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}